/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ServeVideo': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, { error: string }>, never>
    'RenderVideo': EventHandler<{ owner: string; repo: string; jobId: string; starData: { user: string; userAvatarUrl: string; repository: string; stars: number; stargazers: Array<string> }; theme?: 'dark' | 'light' }, never>
    'ProcessGitHubStars': EventHandler<{ owner: string; repo: string; jobId: string; theme?: 'dark' | 'light' }, { topic: 'render-video'; data: { owner: string; repo: string; jobId: string; starData: { user: string; userAvatarUrl: string; repository: string; stars: number; stargazers: Array<string> }; theme?: 'dark' | 'light' } }>
    'GetStarsData': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { repository: { name: string; full_name: string; description: unknown; total_stars: number; forks: number; created_at: string; owner: { login: string; avatar_url: string } }; stars: { total: number; timeline: Array<{ date: string; count: number; cumulative: number }>; recent: Array<{ user: string; avatar_url: string; starred_at: string }> }; generatedAt: string }> | ApiResponse<404, { error: string }>, never>
    'GetJobStatus': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { status: 'pending' | 'processing' | 'completed' | 'failed'; data?: unknown; error?: string }> | ApiResponse<404, { error: string }>, never>
    'FetchGitHubStars': ApiRouteHandler<{ owner: string; repo: string; theme?: 'dark' | 'light' }, ApiResponse<200, { success: boolean; message: string; jobId: string }> | ApiResponse<400, { error: string }> | ApiResponse<500, { error: string }>, { topic: 'process-github-stars'; data: { owner: string; repo: string; jobId: string; theme?: 'dark' | 'light' } }>
  }
}